import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import type { DomainManifestV1 } from "@examen-sw1/spring-generator";
import { executeAssistantCommand, type AssistantHttpAdapter, type AssistantHttpRequest, type AssistantHttpResponse } from "./index.js";

const ops = [{ name: "countUsuario", method: "GET", path: "/api/v1/usuario/count" }, { name: "createUsuario", method: "POST", path: "/api/v1/usuario" }, { name: "deleteUsuario", method: "DELETE", path: "/api/v1/usuario/{id}" }, { name: "getUsuario", method: "GET", path: "/api/v1/usuario/{id}" }, { name: "getUsuarioRelation", method: "GET", path: "/api/v1/usuario/{id}/relations/{relation}" }, { name: "listUsuario", method: "GET", path: "/api/v1/usuario" }, { name: "updateUsuario", method: "PATCH", path: "/api/v1/usuario/{id}" }] as const;
const manifest: DomainManifestV1 = { schemaVersion: 1, entities: [{ name: "usuario", resourceName: "usuario", attributes: [{ name: "id", type: "BIGINT", required: true, identifier: true, unique: false, searchable: false, sortable: true, defaultSort: "ASC" }, { name: "nombre", type: "VARCHAR", required: true, identifier: false, unique: false, searchable: true, sortable: false, defaultSort: null }, { name: "activo", type: "BOOLEAN", required: false, identifier: false, unique: false, searchable: false, sortable: false, defaultSort: null }, { name: "saldo", type: "NUMERIC", required: false, identifier: false, unique: false, searchable: false, sortable: false, defaultSort: null }], relations: [{ name: "rol", target: "usuario", cardinality: "MANY_TO_ONE", lifecycle: "NONE", required: false }], operations: ops }] };
const fake = (response: AssistantHttpResponse<unknown> = { status: 200, data: { ok: true } }) => { const calls: AssistantHttpRequest[] = []; const adapter: AssistantHttpAdapter = { request: async <T>(request: AssistantHttpRequest) => { calls.push(request); return response as AssistantHttpResponse<T>; } }; return { adapter, calls }; };
const code = (result: Awaited<ReturnType<typeof executeAssistantCommand>>) => result.ok ? undefined : result.details?.[0]?.code;

describe("executeAssistantCommand", () => {
  it("valida antes de IO", async () => { const { adapter, calls } = fake(); expect(code(await executeAssistantCommand({ operation: "LIST", entity: "ausente" }, manifest, adapter))).toBe("UNKNOWN_ENTITY"); expect(calls).toHaveLength(0); });
  it("resuelve LIST aun si count aparece antes", async () => { const { adapter, calls } = fake(); await executeAssistantCommand({ operation: "LIST", entity: "usuario" }, manifest, adapter); expect(calls[0]).toMatchObject({ method: "GET", path: "/api/v1/usuario" }); });
  it("resuelve GET, CREATE, UPDATE y COUNT", async () => { const { adapter, calls } = fake({ status: 200, data: { count: 3 } }); await executeAssistantCommand({ operation: "GET", entity: "usuario", identifier: 1 }, manifest, adapter); await executeAssistantCommand({ operation: "CREATE", entity: "usuario", fields: { id: 1, nombre: "Ana" } }, manifest, adapter); await executeAssistantCommand({ operation: "UPDATE", entity: "usuario", identifier: 1, fields: { nombre: "B" } }, manifest, adapter); const count = await executeAssistantCommand({ operation: "COUNT", entity: "usuario" }, manifest, adapter); expect(calls.map((item) => [item.method, item.path])).toEqual([["GET", "/api/v1/usuario/1"], ["POST", "/api/v1/usuario"], ["PATCH", "/api/v1/usuario/1"], ["GET", "/api/v1/usuario/count"]]); expect(count).toMatchObject({ ok: true, data: { count: 3 } }); });
  it("serializa SEARCH con q y filtros repetidos eq", async () => { const { adapter, calls } = fake(); await executeAssistantCommand({ operation: "SEARCH", entity: "usuario", criteria: { query: "Ana", fields: { activo: true, saldo: 15.5 } } }, manifest, adapter); expect(calls[0]?.query).toEqual([["q", "Ana"], ["filter", "activo:eq:true"], ["filter", "saldo:eq:15.5"]]); });
  it("exige confirmación DELETE", async () => { const { adapter, calls } = fake({ status: 204 }); const rejected = await executeAssistantCommand({ operation: "DELETE", entity: "usuario", identifier: 1 }, manifest, adapter); const accepted = await executeAssistantCommand({ operation: "DELETE", entity: "usuario", identifier: 1 }, manifest, adapter, { confirmDelete: true }); expect(rejected).toMatchObject({ ok: false, code: "CONFIRMATION_REQUIRED" }); expect(accepted).toMatchObject({ ok: true, data: undefined }); expect(calls).toHaveLength(1); });
  it("resuelve LIST relation y rechaza SEARCH/COUNT relation sin IO", async () => { const { adapter, calls } = fake(); await executeAssistantCommand({ operation: "LIST", entity: "usuario", relation: { name: "rol", sourceIdentifier: 1 } }, manifest, adapter); expect(calls[0]?.path).toBe("/api/v1/usuario/1/relations/rol"); expect(code(await executeAssistantCommand({ operation: "SEARCH", entity: "usuario", criteria: { query: "A" }, relation: { name: "rol", sourceIdentifier: 1 } }, manifest, adapter))).toBe("UNSUPPORTED_RELATION_OPERATION"); expect(code(await executeAssistantCommand({ operation: "COUNT", entity: "usuario", relation: { name: "rol", sourceIdentifier: 1 } }, manifest, adapter))).toBe("UNSUPPORTED_RELATION_OPERATION"); expect(calls).toHaveLength(1); });
  it("mapea estados y excepciones del adapter", async () => { const bad = fake({ status: 500 }); expect(code(await executeAssistantCommand({ operation: "LIST", entity: "usuario" }, manifest, bad.adapter))).toBe("HTTP_ERROR"); const throwing: AssistantHttpAdapter = { request: async () => { throw new Error("fallo"); } }; expect(code(await executeAssistantCommand({ operation: "LIST", entity: "usuario" }, manifest, throwing))).toBe("ADAPTER_ERROR"); });
  it("no importa transporte concreto", async () => { const source = await readFile(new URL("./executor.ts", import.meta.url), "utf8"); expect(source).not.toMatch(/\bfetch\b|\baxios\b|node:(?:http|https)|https?:\/\//); });
});
