import { ForbiddenException, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { strFromU8, unzipSync } from "fflate";
import { describe, expect, it, vi } from "vitest";
import type { CanonicalUmlModel } from "@examen-sw1/uml-core";
import { FrontendExportService } from "./frontend-export.service";

const projectId = "11111111-1111-4111-8111-111111111111"; const userId = "22222222-2222-4222-8222-222222222222";
const model = (): CanonicalUmlModel => ({ packages: [], enumerations: [], relationships: [], classes: [{ id: "33333333-3333-4333-8333-333333333333", name: "Rol", visibility: "public", operations: [], generationMetadata: { entity: true }, attributes: [{ id: "44444444-4444-4444-8444-444444444444", name: "id", visibility: "private", type: { kind: "primitive", name: "integer" }, generationMetadata: { identifier: true } }, { id: "55555555-5555-4555-8555-555555555555", name: "nombre", visibility: "private", type: { kind: "primitive", name: "string" }, generationMetadata: { required: true } }] }] });
const setup = (uml: CanonicalUmlModel | null = model()) => { const findProject = vi.fn().mockResolvedValue(uml ? { document: { uml, layout: { elements: [] } } } : null); const requireView = vi.fn().mockResolvedValue("VIEWER"); return { exporter: new FrontendExportService({ findProject } as never, { requireView } as never), findProject, requireView }; };

describe("FrontendExportService", () => {
  it("genera un ZIP standalone desde document.uml", async () => { const { exporter, findProject, requireView } = setup(); const files = unzipSync((await exporter.exportProject(projectId, userId)).zip); const packageJson = strFromU8(files["package.json"]!); expect(requireView).toHaveBeenCalledWith(projectId, userId); expect(findProject).toHaveBeenCalledWith(projectId); expect(Object.keys(files)).toEqual(expect.arrayContaining(["app/page.tsx", "app/api.ts", "app/domain.ts", "app/layout.tsx", "package.json"])); expect(packageJson).not.toContain("assistant-core"); expect(packageJson).not.toContain("file:"); expect(strFromU8(files["app/domain.ts"]!)).toContain('"rol"'); });
  it("rechaza acceso antes de cargar proyecto", async () => { const findProject = vi.fn(); const exporter = new FrontendExportService({ findProject } as never, { requireView: vi.fn().mockRejectedValue(new ForbiddenException()) } as never); await expect(exporter.exportProject(projectId, userId)).rejects.toBeInstanceOf(ForbiddenException); expect(findProject).not.toHaveBeenCalled(); });
  it("rechaza proyecto inexistente y modelos inválidos", async () => { await expect(setup(null).exporter.exportProject(projectId, userId)).rejects.toBeInstanceOf(NotFoundException); const without = new FrontendExportService({ findProject: vi.fn().mockResolvedValue({ document: undefined }) } as never, { requireView: vi.fn() } as never); await expect(without.exportProject(projectId, userId)).rejects.toBeInstanceOf(UnprocessableEntityException); await expect(setup({ packages: [], enumerations: [], relationships: [], classes: [] }).exporter.exportProject(projectId, userId)).rejects.toBeInstanceOf(UnprocessableEntityException); });
  it("no altera el frontend cuando cambia solo DiagramLayout", async () => { const uml = model(); const exportWithLayout = async (layout: unknown) => { const exporter = new FrontendExportService({ findProject: vi.fn().mockResolvedValue({ document: { uml, layout } }) } as never, { requireView: vi.fn() } as never); return unzipSync((await exporter.exportProject(projectId, userId)).zip); }; const left = await exportWithLayout({ elements: [{ elementId: "rol", x: 10, y: 20 }] }); const right = await exportWithLayout({ elements: [{ elementId: "rol", x: 900, y: 700 }] }); for (const path of ["package.json", "app/page.tsx", "app/api.ts", "app/domain.ts", "app/layout.tsx"]) expect(strFromU8(left[path]!)).toBe(strFromU8(right[path]!)); });
});
