import type { FrontendGeneratorInput } from "./model.js";

const source = { elementId: "11111111-1111-4111-8111-111111111111", path: "tables[0]" };
const operations = (name: string, path: string) => [
  { name: `count${name}`, method: "GET" as const, path: `${path}/count` }, { name: `create${name}`, method: "POST" as const, path }, { name: `list${name}`, method: "GET" as const, path }, { name: `get${name}`, method: "GET" as const, path: `${path}/{id}` }, { name: `update${name}`, method: "PATCH" as const, path: `${path}/{id}` }, { name: `delete${name}`, method: "DELETE" as const, path: `${path}/{id}` },
];
const attribute = (name: string, type: "VARCHAR" | "BIGINT" | "BOOLEAN" | "NUMERIC" | "DATE", identifier = false, searchable = false) => ({ name, type, required: true, identifier, unique: false, searchable, sortable: identifier || searchable, defaultSort: identifier ? "ASC" as const : null });

export const frontendFixture: FrontendGeneratorInput = {
  relationalModel: { tables: [{ source, name: "rol", primaryKey: "id", columns: [{ source, name: "id", type: "BIGINT", nullable: false, identifier: true, unique: false }, { source, name: "nombre", type: "VARCHAR", nullable: false, identifier: false, unique: true }], uniqueConstraints: [], indexes: [], foreignKeys: [] }, { source, name: "usuario", primaryKey: "id", columns: [{ source, name: "id", type: "BIGINT", nullable: false, identifier: true, unique: false }, { source, name: "nombre", type: "VARCHAR", nullable: false, identifier: false, unique: false }, { source, name: "activo", type: "BOOLEAN", nullable: false, identifier: false, unique: false }, { source, name: "fechaRegistro", type: "DATE", nullable: false, identifier: false, unique: false }, { source, name: "saldo", type: "NUMERIC", nullable: false, identifier: false, unique: false }, { source, name: "rolId", type: "BIGINT", nullable: false, identifier: false, unique: false }], uniqueConstraints: [], indexes: [], foreignKeys: [{ source, name: "fk_usuario_rol", column: "rolId", targetTable: "rol", targetColumn: "id", lifecycle: "NONE" }] }], enums: [], relations: [{ source, cardinality: "MANY_TO_ONE", sourceTable: "usuario", targetTable: "rol", foreignKey: "fk_usuario_rol", lifecycle: "NONE" }], diagnostics: [], hasErrors: false, success: true },
  domainManifest: { schemaVersion: 1, entities: [{ name: "rol", resourceName: "rol", attributes: [attribute("id", "BIGINT", true), attribute("nombre", "VARCHAR", false, true)], relations: [], operations: operations("Rol", "/api/v1/rol") }, { name: "usuario", resourceName: "usuario", attributes: [attribute("id", "BIGINT", true), attribute("nombre", "VARCHAR", false, true), attribute("activo", "BOOLEAN"), attribute("fechaRegistro", "DATE"), attribute("saldo", "NUMERIC")], relations: [{ name: "rol", target: "rol", cardinality: "MANY_TO_ONE", lifecycle: "NONE", required: true }], operations: operations("Usuario", "/api/v1/usuario") }] },
  openApi: { paths: { "/api/v1/rol/count": { get: { operationId: "countRol" } }, "/api/v1/rol": { get: { operationId: "listRol" }, post: { operationId: "createRol", requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/CreateRolRequest" } } } } } }, "/api/v1/rol/{id}": { get: { operationId: "getRol" }, patch: { operationId: "updateRol", requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/UpdateRolRequest" } } } } }, delete: { operationId: "deleteRol" } }, "/api/v1/usuario/count": { get: { operationId: "countUsuario" } }, "/api/v1/usuario": { get: { operationId: "listUsuario" }, post: { operationId: "createUsuario", requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/CreateUsuarioRequest" } } } } } }, "/api/v1/usuario/{id}": { get: { operationId: "getUsuario" }, patch: { operationId: "updateUsuario", requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/UpdateUsuarioRequest" } } } } }, delete: { operationId: "deleteUsuario" } } }, components: { schemas: { CreateRolRequest: { properties: { id: { type: "integer" }, nombre: { type: "string" } }, required: ["id", "nombre"] }, UpdateRolRequest: { properties: { nombre: { type: "string" } } }, CreateUsuarioRequest: { properties: { activo: { type: "boolean" }, fechaRegistro: { type: "string" }, id: { type: "integer" }, nombre: { type: "string" }, rolId: { type: "integer" }, saldo: { type: "number" } }, required: ["activo", "fechaRegistro", "id", "nombre", "rolId", "saldo"] }, UpdateUsuarioRequest: { properties: { activo: { $ref: "#/components/schemas/PatchFieldBoolean" }, fechaRegistro: { $ref: "#/components/schemas/PatchFieldLocalDate" }, nombre: { $ref: "#/components/schemas/PatchFieldString" }, rolId: { $ref: "#/components/schemas/PatchFieldLong" }, saldo: { $ref: "#/components/schemas/PatchFieldBigDecimal" } } } } } },
  assistantCoreDependency: "file:../assistant-core",
};
