import { describe, expect, it } from "vitest";
import { generateFrontend } from "./generator.js";
import { frontendFixture } from "./frontend-fixture.js";

describe("FrontendGenerator", () => {
  const generatorInput = frontendFixture;
  it("genera el árbol Next determinista sin alterar el Manifest", () => {
    const manifest = structuredClone(frontendFixture.domainManifest); const first = generateFrontend(generatorInput); const second = generateFrontend(structuredClone(generatorInput));
    expect(first).toEqual(second); expect(first.map((file) => file.path)).toEqual(expect.arrayContaining(["capacitor.config.ts", "scripts/configure-android.mjs", "app/lan-config.ts"])); expect(first.find((file) => file.path === "next.config.ts")?.content).toContain('output: "export"'); const packageJson = JSON.parse(first.find((file) => file.path === "package.json")!.content); expect(packageJson.dependencies["@capacitor/core"]).toBe("7.6.9"); expect(packageJson.devDependencies["@capacitor/cli"]).toBe("7.6.9"); expect(packageJson.devDependencies["@capacitor/android"]).toBe("7.6.9"); const capacitor = first.find((file) => file.path === "capacitor.config.ts")?.content; expect(capacitor).toContain('webDir: "out"'); expect(capacitor).toContain('androidScheme: "http"'); expect(capacitor).not.toContain("allowMixedContent"); expect(capacitor).not.toContain("192.168.1.4"); expect(first.find((file) => file.path === "scripts/configure-android.mjs")?.content).toContain("android.permission.RECORD_AUDIO"); expect(frontendFixture.domainManifest).toEqual(manifest);
  });
  it("incluye CRUD, consulta, relaciones, estados y configuración local segura", () => {
    const page = generateFrontend(generatorInput).find((file) => file.path === "app/page.tsx")!.content;
    expect(page).toContain("NEXT_PUBLIC_API_BASE_URL"); expect(page).toContain("Confirmar eliminación"); expect(page).toContain("No hay registros."); expect(page).toContain("No se pudieron consultar los datos"); expect(page).toContain("attribute.identifier");
  });
  it("genera configuración LAN limitada y permisos Android mínimos", () => {
    const files = generateFrontend(generatorInput); const lan = files.find((file) => file.path === "app/lan-config.ts")!.content; const voice = files.find((file) => file.path === "app/voice-transcript-input.tsx")!.content; const manifest = files.find((file) => file.path === "scripts/configure-android.mjs")!.content;
    expect(lan).toContain("/speech/recognize"); expect(lan).toContain("localhost representa el teléfono"); expect(lan).toContain("65535"); expect(voice).toContain("HOST_UNAVAILABLE"); expect(voice).toContain("TIMEOUT"); expect(voice).toContain("getUserMedia"); expect(manifest).toContain("android.permission.RECORD_AUDIO"); expect(manifest).toContain("android.permission.MODIFY_AUDIO_SETTINGS"); expect(manifest).not.toContain("CAMERA"); expect(manifest).not.toContain("LOCATION");
  });
  it("limita formularios a campos mutables contractuales", () => {
    const page = generateFrontend(generatorInput).find((file) => file.path === "app/page.tsx")!.content;
    expect(page).toContain("entity.createFields"); expect(page).toContain("entity.updateFields"); expect(page).toContain("field.wireName"); expect(page).toContain("field.schemaType"); expect(page).toContain("field.required"); expect(page).not.toContain("entity.attributes.filter((field) => creating || !field.identifier)"); expect(page).not.toContain("entity.relations.map((relation) => <TextField");
  });
  it("incluye selector contractual de relaciones con carga, dedupe y coerción tipada", () => {
    const page = generateFrontend(generatorInput).find((file) => file.path === "app/page.tsx")!.content;
    expect(page).toContain("candidate.name === relationTarget || candidate.resourceName === relationTarget"); expect(page).toContain("candidate.method === \"GET\" && !candidate.path.includes(\"{\") && candidate.name.toLowerCase().startsWith(\"list\")"); expect(page).toContain("page=0&size=100"); expect(page).toContain("Array.isArray(result) ? result : result.content ?? []"); expect(page).toContain("relationOptionsRequested.current.has(relationTarget)"); expect(page).toContain("relationOptionsRequested.current.delete(relationTarget)"); expect(page).toContain("<MuiTextField {...props} select disabled="); expect(page).toContain("<MenuItem value=\"\">Seleccionar...</MenuItem>"); expect(page).toContain("String(option[identifier.name])"); expect(page).toContain("No se encontró la entidad relacionada."); expect(page).toContain("La entidad relacionada no tiene identificador."); expect(page).toContain("Cargando opciones..."); expect(page).toContain("field.schemaType === \"integer\" || field.schemaType === \"number\""); expect(page).toContain("Number(rawValue)"); expect(page).not.toContain("wireName === \"rolId\"");
  });
  it("genera un panel guiado con resultados y confirmación destructiva", () => {
    const panel = generateFrontend(generatorInput).find((file) => file.path === "app/assistant-panel.tsx")!.content;
    const page = generateFrontend(generatorInput).find((file) => file.path === "app/page.tsx")!.content;
    expect(panel).not.toContain("Campos JSON"); expect(panel).toContain("parseStructuredAssistantOutput"); expect(panel).toContain("validateAssistantCommand"); expect(panel).toContain("executeAssistantCommand"); expect(panel).not.toContain("UmlCommandBus"); expect(panel).not.toContain("CanonicalUmlModel"); expect(panel).toContain("fieldRows"); expect(panel).toContain("confirmDelete"); expect(panel).toContain("ASSISTANT_OPERATIONS.map"); expect(panel).toContain("domainManifest.entities.map"); expect(page).toContain("AssistantTextProposal"); expect(page).toContain("assistantText");
  });
  it("mantiene el fixture alineado con las rutas y atributos del backend manual", () => { const usuario = frontendFixture.domainManifest.entities.find((entity) => entity.name === "usuario")!; expect(usuario.resourceName).toBe("usuario"); expect(usuario.operations.find((item) => item.name === "listUsuario")?.path).toBe("/api/v1/usuario"); expect(usuario.attributes.map((attribute) => attribute.name)).toEqual(expect.arrayContaining(["id", "nombre", "activo", "fechaRegistro", "saldo"])); expect(usuario.attributes.map((attribute) => attribute.name)).not.toContain("email"); expect(usuario.relations).toContainEqual(expect.objectContaining({ name: "rol", target: "rol" })); expect(frontendFixture.openApi.components?.schemas?.CreateUsuarioRequest?.properties?.rolId).toBeDefined(); expect(Object.keys(frontendFixture.openApi.paths)).toContain("/api/v1/usuario"); expect(JSON.stringify(frontendFixture)).not.toContain("/api/v1/usuarios"); const panel = generateFrontend(generatorInput).find((file) => file.path === "app/assistant-panel.tsx")!.content; const domain = generateFrontend(generatorInput).find((file) => file.path === "app/domain.ts")!.content; expect(panel).toContain("entity.attributes"); expect(domain).toContain('"nombre"'); });
  it("conserva COUNT en el fixture y dominio generado", () => { const usuario = frontendFixture.domainManifest.entities.find((entity) => entity.name === "usuario")!; const rol = frontendFixture.domainManifest.entities.find((entity) => entity.name === "rol")!; expect(usuario.operations.find((item) => item.name === "countUsuario")).toMatchObject({ method: "GET", path: "/api/v1/usuario/count" }); expect(rol.operations.find((item) => item.name === "countRol")).toMatchObject({ method: "GET", path: "/api/v1/rol/count" }); expect(Object.keys(frontendFixture.openApi.paths)).toContain("/api/v1/usuario/count"); expect(generateFrontend(generatorInput).find((file) => file.path === "app/domain.ts")!.content).toContain('"countUsuario"'); });
  it("rechaza contratos que no coinciden", () => expect(() => generateFrontend({ ...generatorInput, openApi: { paths: {} } })).toThrow("OpenAPI no verifica"));
});
