import { rm } from "node:fs/promises";
import { spawn } from "node:child_process";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { generateFrontendToOutput } from "./generate-to-output.js";

const source = { elementId: "11111111-1111-4111-8111-111111111111", path: "tables[0]" };
const generatorRoot = fileURLToPath(new URL("../", import.meta.url));
const smokeRoot = resolve(generatorRoot, ".generated-assistant-smoke");
const output = resolve(smokeRoot, "frontend");
const assistantCoreRoot = resolve(generatorRoot, "..", "assistant-core");
const input = { relationalModel: { tables: [{ source, name: "usuario", primaryKey: "id", columns: [{ source, name: "id", type: "BIGINT" as const, nullable: false, identifier: true, unique: false }, { source, name: "email", type: "VARCHAR" as const, nullable: false, identifier: false, unique: true, searchable: true, sortable: true }], uniqueConstraints: [], indexes: [], foreignKeys: [] }], enums: [], relations: [], diagnostics: [], hasErrors: false, success: true }, domainManifest: { schemaVersion: 1 as const, entities: [{ name: "usuario", resourceName: "usuarios", attributes: [{ name: "id", type: "BIGINT" as const, required: true, identifier: true, unique: false, searchable: false, sortable: true, defaultSort: "ASC" as const }, { name: "email", type: "VARCHAR" as const, required: true, identifier: false, unique: true, searchable: true, sortable: true, defaultSort: null }], relations: [], operations: [{ name: "createUsuario", method: "POST" as const, path: "/api/v1/usuarios" }, { name: "listUsuario", method: "GET" as const, path: "/api/v1/usuarios" }, { name: "getUsuario", method: "GET" as const, path: "/api/v1/usuarios/{id}" }, { name: "updateUsuario", method: "PATCH" as const, path: "/api/v1/usuarios/{id}" }, { name: "deleteUsuario", method: "DELETE" as const, path: "/api/v1/usuarios/{id}" }] }] }, openApi: { paths: { "/api/v1/usuarios": { post: { operationId: "createUsuario" }, get: { operationId: "listUsuario" } }, "/api/v1/usuarios/{id}": { get: { operationId: "getUsuario" }, patch: { operationId: "updateUsuario" }, delete: { operationId: "deleteUsuario" } } } } };
const smokeOpenApi = { paths: { "/api/v1/usuarios": { post: { operationId: "createUsuario", requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/CreateUsuarioRequest" } } } } }, get: { operationId: "listUsuario" } }, "/api/v1/usuarios/{id}": { get: { operationId: "getUsuario" }, patch: { operationId: "updateUsuario", requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/UpdateUsuarioRequest" } } } } }, delete: { operationId: "deleteUsuario" } } }, components: { schemas: { CreateUsuarioRequest: { properties: { id: { type: "integer" }, email: { type: "string" } }, required: ["id", "email"] }, UpdateUsuarioRequest: { properties: { email: { type: "string" } }, required: ["email"] } } } };

function run(command: string): Promise<void> { return new Promise((resolveRun, reject) => { const child = spawn(process.env.ComSpec ?? "cmd.exe", ["/d", "/c", command], { cwd: output, stdio: "inherit" }); child.on("error", reject); child.on("close", (code) => code === 0 ? resolveRun() : reject(new Error(`El comando generado terminó con ${code ?? "desconocido"}.`))); }); }
try { await rm(smokeRoot, { recursive: true, force: true }); await generateFrontendToOutput({ ...input, openApi: smokeOpenApi }, output, assistantCoreRoot); await run("npm install --ignore-scripts"); await run("npm run build"); } finally { await rm(smokeRoot, { recursive: true, force: true }); }
