import { describe, expect, it } from "vitest";
import { generateFrontend } from "./generator.js";
import { frontendFixture } from "./frontend-fixture.js";

describe("FrontendGenerator", () => {
  const generatorInput = frontendFixture;
  it("genera el árbol Next determinista sin alterar el Manifest", () => {
    const manifest = structuredClone(frontendFixture.domainManifest); const first = generateFrontend(generatorInput); const second = generateFrontend(structuredClone(generatorInput));
    expect(first).toEqual(second); expect(first.map((file) => file.path)).toEqual([".env.example", "app/assistant-panel.tsx", "app/domain.ts", "app/layout.tsx", "app/page.tsx", "next.config.ts", "package.json", "tsconfig.json"]); expect(first.find((file) => file.path === ".env.example")?.content).toContain("NEXT_PUBLIC_API_BASE_URL"); expect(JSON.parse(first.find((file) => file.path === "package.json")!.content).dependencies["@examen-sw1/assistant-core"]).toBe("file:../assistant-core"); expect(frontendFixture.domainManifest).toEqual(manifest);
  });
  it("incluye CRUD, consulta, relaciones, estados y configuración local segura", () => {
    const page = generateFrontend(generatorInput).find((file) => file.path === "app/page.tsx")!.content;
    expect(page).toContain("NEXT_PUBLIC_API_BASE_URL"); expect(page).toContain("Confirmar eliminación"); expect(page).toContain("No hay registros."); expect(page).toContain("No se pudieron consultar los datos"); expect(page).toContain("attribute.identifier");
  });
  it("limita formularios a campos mutables contractuales", () => {
    const page = generateFrontend(generatorInput).find((file) => file.path === "app/page.tsx")!.content;
    expect(page).toContain("entity.createFields"); expect(page).toContain("entity.updateFields"); expect(page).toContain("field.wireName"); expect(page).toContain("field.schemaType"); expect(page).toContain("field.required"); expect(page).not.toContain("entity.attributes.filter((field) => creating || !field.identifier)"); expect(page).not.toContain("entity.relations.map((relation) => <TextField");
  });
  it("incluye selector contractual de relaciones con carga, dedupe y coerción tipada", () => {
    const page = generateFrontend(generatorInput).find((file) => file.path === "app/page.tsx")!.content;
    expect(page).toContain("candidate.name === relationTarget || candidate.resourceName === relationTarget"); expect(page).toContain("candidate.method === \"GET\" && !candidate.path.includes(\"{\") && candidate.name.toLowerCase().startsWith(\"list\")"); expect(page).toContain("page=0&size=100"); expect(page).toContain("Array.isArray(result) ? result : result.content ?? []"); expect(page).toContain("relationOptionsRequested.current.has(relationTarget)"); expect(page).toContain("relationOptionsRequested.current.delete(relationTarget)"); expect(page).toContain("<MuiTextField {...props} select disabled="); expect(page).toContain("<MenuItem value=\"\">Seleccionar...</MenuItem>"); expect(page).toContain("String(option[identifier.name])"); expect(page).toContain("No se encontró la entidad relacionada."); expect(page).toContain("La entidad relacionada no tiene identificador."); expect(page).toContain("Cargando opciones..."); expect(page).toContain("field.schemaType === \"integer\" || field.schemaType === \"number\""); expect(page).toContain("Number(rawValue)"); expect(page).not.toContain("wireName === \"rolId\"");
  });
  it("genera un panel guiado con resultados y confirmación destructiva", () => {
    const panel = generateFrontend(generatorInput).find((file) => file.path === "app/assistant-panel.tsx")!.content;
    const page = generateFrontend(generatorInput).find((file) => file.path === "app/page.tsx")!.content;
    expect(panel).not.toContain("Campos JSON"); expect(panel).not.toContain("JSON.parse"); expect(panel).toContain("fieldRows"); expect(panel).toContain("Agregar campo"); expect(panel).toContain("Eliminar"); expect(panel).toContain("entity.attributes"); expect(panel).toContain("!attribute.identifier"); expect(panel).toContain("selected.includes"); expect(panel).toContain("Number(row.value)"); expect(panel).toContain("row.value === \"true\""); expect(panel).toContain("criteria: { query: query || undefined"); expect(panel).toContain("executeAssistantCommand(next, domainManifest, adapter"); expect(panel).toContain("confirmDelete"); expect(panel).toContain("<Typography variant=\"body2\" fontWeight={600}>Operación</Typography><Select value={operation}"); expect(panel).toContain("<Typography variant=\"body2\" fontWeight={600}>Entidad</Typography><Select value={entityName}"); expect(panel).not.toContain("InputLabel"); expect(panel).toContain("ASSISTANT_OPERATIONS.map"); expect(panel).toContain("domainManifest.entities.map"); expect(page).toContain("import { AssistantPanel } from \"./assistant-panel\""); expect(page).toContain("<AssistantPanel />");
  });
  it("mantiene el fixture alineado con las rutas y atributos del backend manual", () => { const usuario = frontendFixture.domainManifest.entities.find((entity) => entity.name === "usuario")!; expect(usuario.resourceName).toBe("usuario"); expect(usuario.operations.find((item) => item.name === "listUsuario")?.path).toBe("/api/v1/usuario"); expect(usuario.attributes.map((attribute) => attribute.name)).toEqual(expect.arrayContaining(["id", "nombre", "activo", "fechaRegistro", "saldo"])); expect(usuario.attributes.map((attribute) => attribute.name)).not.toContain("email"); expect(usuario.relations).toContainEqual(expect.objectContaining({ name: "rol", target: "rol" })); expect(frontendFixture.openApi.components?.schemas?.CreateUsuarioRequest?.properties?.rolId).toBeDefined(); expect(Object.keys(frontendFixture.openApi.paths)).toContain("/api/v1/usuario"); expect(JSON.stringify(frontendFixture)).not.toContain("/api/v1/usuarios"); const panel = generateFrontend(generatorInput).find((file) => file.path === "app/assistant-panel.tsx")!.content; const domain = generateFrontend(generatorInput).find((file) => file.path === "app/domain.ts")!.content; expect(panel).toContain("entity.attributes"); expect(domain).toContain('"nombre"'); });
  it("conserva COUNT en el fixture y dominio generado", () => { const usuario = frontendFixture.domainManifest.entities.find((entity) => entity.name === "usuario")!; const rol = frontendFixture.domainManifest.entities.find((entity) => entity.name === "rol")!; expect(usuario.operations.find((item) => item.name === "countUsuario")).toMatchObject({ method: "GET", path: "/api/v1/usuario/count" }); expect(rol.operations.find((item) => item.name === "countRol")).toMatchObject({ method: "GET", path: "/api/v1/rol/count" }); expect(Object.keys(frontendFixture.openApi.paths)).toContain("/api/v1/usuario/count"); expect(generateFrontend(generatorInput).find((file) => file.path === "app/domain.ts")!.content).toContain('"countUsuario"'); });
  it("rechaza contratos que no coinciden", () => expect(() => generateFrontend({ ...generatorInput, openApi: { paths: {} } })).toThrow("OpenAPI no verifica"));
});
